DROP TABLE IF EXISTS h57dbanew.M_N1,h57dbanew.M_EMP;

CREATE TABLE h57dbanew.M_EMP (
	EMP_ID CHAR(10) NOT NULL,
	EMP_NAME VARCHAR(20) NOT NULL,
	EMP_CD CHAR(6) NOT NULL,
	AFFL_CD CHAR(3) NOT NULL,
	CONSTRAINT PK_M_EMP PRIMARY KEY (EMP_ID)
);

CREATE TABLE h57dbanew.M_N1 (
	EMP_ID CHAR(10) NOT NULL,
	FK_EMP_ID CHAR(10),
	EMP_NAME VARCHAR(20) NOT NULL,
	EMP_CD CHAR(6) NOT NULL,
	AFFL_CD CHAR(3) NOT NULL,
	ADM_FLG BOOLEAN DEFAULT FALSE,
	CONSTRAINT PK_M_N1 PRIMARY KEY (EMP_ID),
	FOREIGN KEY (FK_EMP_ID) REFERENCES h57dbanew.M_EMP(EMP_ID)
	ON DELETE SET NULL
);